name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    run-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-lastest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          node-version: ${{ martix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Lint
        run: pnpm run lint
